In [1]:
import numpy as np

# Define a 3x3 matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Define a 3x1 vector
vector = np.array([1, 0, 1])

# Multiply the matrix by the vector
result = np.dot(matrix, vector)

print("Matrix:")
print(matrix)
print("\nVector:")
print(vector)
print("\nResult of matrix-vector multiplication:")
print(result)


Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Vector:
[1 0 1]

Result of matrix-vector multiplication:
[ 4 10 16]
